version: "3.7"

services:
  userrolesdb:
    image: postgres:18.4@sha256:3a82e1f56c8f0f5616a11103ac3d47e632c3938698946a7ad26da0df1334744a
    container_name: userrolesdb
    ports:
      - "127.0.0.1:10101:5432"
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=userrolesdb
