version: "3.7"

services:
  userrolesdb:
    image: postgres:18.4@sha256:311136771dca6826c3b6e691ebf8cb6e896e165074bc57a728f9619f25f0c4c7
    container_name: userrolesdb
    ports:
      - "127.0.0.1:10101:5432"
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=userrolesdb
