version: "3.7"

services:
  userrolesdb:
    image: postgres:18.3@sha256:52e6ffd11fddd081ae63880b635b2a61c14008c17fc98cdc7ce5472265516dd0
    container_name: userrolesdb
    ports:
      - "127.0.0.1:10101:5432"
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=userrolesdb
